//using Microsoft.Data.Sqlite;
//using System;

//class Program
//{
//    static void Main()
//    {
//        string connectionString = "Data Source=ConfigHub.db";
        
//        try
//        {
//            using var connection = new SqliteConnection(connectionString);
//            connection.Open();
            
//            // Insert Basecomponent data
//            string[] insertCommands = {
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (2, 'EMP Detail', '16', 'EMP Detail', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (14, 'ContractDetail', '16', 'Contract Detail', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (15, 'Register Form', '16', 'Register Form', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (16, 'DefaultComponent', '0', 'Home', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/jsonformviewer\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (17, 'addition cost', '16', 'addition cost', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (18, 'Sample Grid', '23', 'AG GRID List', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\",\"method\": \"POST\",\"url\": \"/api/controllername/getGridData\",\"datasource\": [{\"Name\": \"John Doe\", \"Age\": 30}, {\"Name\": \"Jane Smith\", \"Age\": 25},{\"Name\": \"Michael Johnson\", \"Age\": 35}, {\"Name\": \"Emily Davis\", \"Age\": 28}]}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (19, 'NatHabbit', '16', 'Nat Habbit', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (20, 'MobileModel', '23', 'Mobile Model', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\",\"method\": \"POST\",\"url\": \"/api/controllername/getGridData\",\"datasource\": [{\"brand\": \"Apple\",\"model\": \"iPhone 14\",\"os\": \"iOS\",\"screenSize\": \"6.1\",\"processor\": \"A15 Bionic\",\"ram\": \"6GB\",\"storage\": \"128GB\",\"battery\": \"3279mAh\",\"color\": \"Midnight\",\"price\": \"799\"},{\"brand\": \"Google\",\"model\": \"Pixel 7\",\"os\": \"Android\",\"screenSize\": \"6.3\",\"processor\": \"Google Tensor G2\",\"ram\": \"8GB\",\"storage\": \"128GB\",\"battery\": \"4355mAh\",\"color\": \"Obsidian\",\"price\": \"599\"},{\"brand\": \"OnePlus\",\"model\": \"OnePlus 11\",\"os\": \"Android\",\"screenSize\": \"6.7\",\"processor\": \"Snapdragon 8 Gen 2\",\"ram\": \"12GB\",\"storage\": \"256GB\",\"battery\": \"5000mAh\",\"color\": \"Titan Black\",\"price\": \"799\"},{\"brand\": \"Samsung\",\"model\": \"Galaxy Z Flip 5\",\"os\": \"Android\",\"screenSize\": \"6.7\",\"processor\": \"Snapdragon 8 Gen 2\",\"ram\": \"8GB\",\"storage\": \"256GB\",\"battery\": \"3700mAh\",\"color\": \"Graphite\",\"price\": \"999\"},{\"brand\": \"Xiaomi\",\"model\": \"Xiaomi 13 Pro\",\"os\": \"Android\",\"screenSize\": \"6.73\",\"processor\": \"Snapdragon 8 Gen 2\",\"ram\": \"12GB\",\"storage\": \"256GB\",\"battery\": \"4820mAh\",\"color\": \"Ceramic White\",\"price\": \"899\"},{\"brand\": \"Sony\",\"model\": \"Xperia 1 V\",\"os\": \"Android\",\"screenSize\": \"6.5\",\"processor\": \"Snapdragon 8 Gen 2\",\"ram\": \"12GB\",\"storage\": \"256GB\",\"battery\": \"5000mAh\",\"color\": \"Black\",\"price\": \"1199\"}]}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (21, 'common grid', '23', 'AG GRID Common', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\",\"method\": \"POST\",\"url\": \"/api/controllername/getGridData\",\"datasource\": [{\"Name\": \"John Doe\", \"Age\": 30}, {\"Name\": \"Jane Smith\", \"Age\": 25},{\"Name\": \"Michael Johnson\", \"Age\": 35}, {\"Name\": \"Emily Davis\", \"Age\": 28}]}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (22, 'boutique', '16', 'Boutique', 1, 0, '{}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (23, 'Grid', '0', 'Grid', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (24, 'string', 'string', 'string', 1, 1, 'string', 'string', 0)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (25, 'MTest', '0', 'Master Test', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 1)",
//                "INSERT OR REPLACE INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES (26, 'Vessel', '0', 'Vessel Detail', 1, 0, '{\"menuicon\": \"far fa-file-alt me-2\",\"routerurl\": \"/adminconfiguration/baseconfiguration\",\"routerparam\": \"\"}', NULL, 0)"
//            };
            
//            foreach (string command in insertCommands)
//            {
//                using var cmd = new SqliteCommand(command, connection);
//                cmd.ExecuteNonQuery();
//            }
            
//            Console.WriteLine("Basecomponent data inserted successfully!");
            
//            // Insert BaseDefinition data
//            string[] baseDefinitionCommands = {
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (1, 2, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"defaultvalue\":\"Name\",\"isvisible\":true,\"isdisable\":true,\"decimalcount\":0,\"minlength\":0,\"maxlength\":100,\"patterntype\":\"NA\",\"minnumber\":0,\"maxnumber\":100,\"isunique\":true,\"isactive\":true}', '{\"lookupid\":1,\"lookupname\":\"Name\",\"lookupdatasource\":\"Names\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (2, 2, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"number\",\"displayname\":\"Age\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Age\",\"placeholder\":\"Age\",\"isrequired\":true,\"defaultvalue\":\"18\",\"isvisible\":true,\"isdisable\":true,\"decimalcount\":0,\"minlength\":0,\"maxlength\":100,\"patterntype\":\"NA\",\"minnumber\":0,\"maxnumber\":100,\"isunique\":true,\"isactive\":true}', '{\"lookupid\":1,\"lookupname\":\"Age\",\"lookupdatasource\":\"Ages\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (3, 2, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Phone\",\"ctrltype\":\"number\",\"displayname\":\"Phone\"}', '{\"ctrlsize\":8,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Phone\",\"placeholder\":\"Phone\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true,\"decimalcount\":0,\"minlength\":0,\"maxlength\":100,\"patterntype\":\"NA\",\"minnumber\":0,\"maxnumber\":100,\"isunique\":true,\"isactive\":true}', '{\"lookupid\":null}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (4, 2, '{\"ctrlgroupname\":\"Employee\",\"groupsequence\":2}', '{\"ctrlname\":\"Salary\",\"ctrltype\":\"number\",\"displayname\":\"Salary\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Salary\",\"placeholder\":\"Salary\",\"isrequired\":true,\"defaultvalue\":\"0\",\"isvisible\":true,\"isdisable\":true,\"decimalcount\":0,\"minlength\":0,\"maxlength\":100,\"patterntype\":\"NA\",\"minnumber\":0,\"maxnumber\":100,\"isunique\":true,\"isactive\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (5, 14, '{\"ctrlgroupname\":\"AngularVersion\",\"groupsequence\":1}', '{\"ctrlname\":\"AngularVersion\",\"ctrltype\":\"select\",\"displayname\":\"Angular Version\"}', '{\"ctrlsize\":12,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"defaultvalue\":\"3\",\"isvisible\":true,\"isdisable\":true,\"decimalcount\":0,\"minlength\":100,\"maxlength\":100,\"patterntype\":\"NA\",\"minnumber\":0,\"maxnumber\":100,\"isunique\":true,\"isactive\":true}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"Angular 14\\\"},{\\\"id\\\":\\\"2\\\",\\\"name\\\":\\\"Angular 15\\\"},{\\\"id\\\":\\\"3\\\",\\\"name\\\":\\\"Angular 16\\\"},{\\\"id\\\":\\\"4\\\",\\\"name\\\":\\\"Angular 17\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (6, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (7, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"number\",\"displayname\":\"Age\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (8, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"Email\",\"ctrltype\":\"email\",\"displayname\":\"Email\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (9, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"Password\",\"ctrltype\":\"password\",\"displayname\":\"Password\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"careerSummary \",\"ctrltype\":\"textarea\",\"displayname\":\"career Summary \"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (11, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"BDegree\",\"ctrltype\":\"checkbox\",\"displayname\":\"Bdegree\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (12, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"MDegree\",\"ctrltype\":\"checkbox\",\"displayname\":\"MDegree\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (13, 15, '{\"ctrlgroupname\":\"approveOrReject\",\"groupsequence\":1}', '{\"ctrlname\":\"approve_reject\",\"ctrltype\":\"radio\",\"displayname\":\"approve\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"approveOrReject\",\"placeholder\":\"approveOrReject\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (14, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"Phone\",\"ctrltype\":\"tel\",\"displayname\":\"Phone\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (15, 15, '{\"ctrlgroupname\":\"RegisterForm\",\"groupsequence\":1}', '{\"ctrlname\":\"DOB\",\"ctrltype\":\"date\",\"displayname\":\"DOB\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Name\",\"placeholder\":\"Name\",\"isrequired\":true,\"isvisible\":true,\"isdisable\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10007, 15, '{\"ctrlgroupname\":\"approveOrReject\",\"groupsequence\":1}', '{\"ctrlname\":\"approve_reject\",\"ctrltype\":\"radio\",\"displayname\":\"Reject\"}', '{\"ctrlsize\":4,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"approveOrReject\",\"placeholder\":\"approveOrReject\",\"isrequired\":true,\"isvisible\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10008, 17, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"First\",\"ctrltype\":\"text\",\"displayname\":\"First Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"First Name\",\"placeholder\":\"First Name\",\"isrequired\":true,\"isvisible\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10009, 17, '{\"ctrlgroupname\":\"Official\",\"groupsequence\":2}', '{\"ctrlname\":\"Email\",\"ctrltype\":\"email\",\"displayname\":\"Email Address\"}', '{\"ctrlsize\":12,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Email\",\"placeholder\":\"Email\",\"isrequired\":true,\"isvisible\":true}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10010, 17, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Last\",\"ctrltype\":\"text\",\"displayname\":\"Last Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":120,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"tooltips\":\"Last\",\"placeholder\":\"Last\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10011, 0, '{}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"grid\",\"displayname\":\"1\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10012, 0, '{\"ctrlgroupname\":\"Name\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"grid\",\"displayname\":\"1\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10013, 18, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"grid\",\"displayname\":\"Name\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10014, 18, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"grid\",\"displayname\":\"Age\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10015, 18, '{\"ctrlgroupname\":\"Employee\",\"groupsequence\":1}', '{\"ctrlname\":\"approveOrReject\",\"ctrltype\":\"grid\",\"displayname\":\"approve Or Reject\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10016, 18, '{\"ctrlgroupname\":\"Employee\",\"groupsequence\":1}', '{\"ctrlname\":\"approve_reject\",\"ctrltype\":\"grid\",\"displayname\":\"approve reject\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10017, 19, '{\"ctrlgroupname\":\"Oil\",\"groupsequence\":1}', '{\"ctrlname\":\"harbal\",\"ctrltype\":\"select\",\"displayname\":\"Harbal\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"alovera\\\"},{\\\"id\\\":\\\"2\\\",\\\"name\\\":\\\"hibiscus\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10018, 19, '{\"ctrlgroupname\":\"Oil\",\"groupsequence\":3}', '{\"ctrlname\":\"Coconut\",\"ctrltype\":\"select\",\"displayname\":\"Coconut\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"purecoconut\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10019, 19, '{\"ctrlgroupname\":\"Oil\",\"groupsequence\":2}', '{\"ctrlname\":\"HarbelQty\",\"ctrltype\":\"select\",\"displayname\":\"Harbel Qty\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\",\"isdisable\":false}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"1000\\\"},{\\\"id\\\":\\\"2\\\",\\\"name\\\":\\\"1500\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10020, 19, '{\"ctrlgroupname\":\"Oil\",\"groupsequence\":4}', '{\"ctrlname\":\"Coconut Qty\",\"ctrltype\":\"select\",\"displayname\":\"Coconut Qty\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"1000\\\"},{\\\"id\\\":\\\"2\\\",\\\"name\\\":\\\"2000\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10021, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"brand\",\"ctrltype\":\"grid\",\"displayname\":\"brand\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10022, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"model\",\"ctrltype\":\"grid\",\"displayname\":\"model\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10023, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"os\",\"ctrltype\":\"grid\",\"displayname\":\"os\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10024, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"processor\",\"ctrltype\":\"grid\",\"displayname\":\"processor\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10025, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"storage\",\"ctrltype\":\"grid\",\"displayname\":\"storage\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10026, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"color\",\"ctrltype\":\"grid\",\"displayname\":\"color\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10027, 20, '{\"ctrlgroupname\":\"Model\",\"groupsequence\":1}', '{\"ctrlname\":\"price\",\"ctrltype\":\"grid\",\"displayname\":\"price\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10028, 21, '{\"ctrlgroupname\":\"Name\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"grid\",\"displayname\":\"Age\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10029, 22, '{\"ctrlgroupname\":\"boutique\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10030, 22, '{\"ctrlgroupname\":\"boutique\",\"groupsequence\":2}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"number\",\"displayname\":\"Age\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10031, 22, '{\"ctrlgroupname\":\"boutique\",\"groupsequence\":2}', '{\"ctrlname\":\"Type\",\"ctrltype\":\"select\",\"displayname\":\"Type\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{\"lookupid\":\"id\",\"lookupname\":\"name\",\"lookupdatasource\":\"[{\\\"id\\\":\\\"1\\\",\\\"name\\\":\\\"1000\\\"},{\\\"id\\\":\\\"2\\\",\\\"name\\\":\\\"2000\\\"}]\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10032, 1, '{\"ctrlgroupname\":\"Name\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10033, 1, '{\"ctrlgroupname\":\"Name\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10034, 25, '{\"ctrlgroupname\":\"Test\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10035, 25, '{\"ctrlgroupname\":\"Personal\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"text\",\"displayname\":\"Age\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10036, 26, '{\"ctrlgroupname\":\"VesselInfo\",\"groupsequence\":1}', '{\"ctrlname\":\"Name\",\"ctrltype\":\"text\",\"displayname\":\"Name\"}', '{\"ctrlsize\":6,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10037, 26, '{\"ctrlgroupname\":\"Bops\",\"groupsequence\":2}', '{\"ctrlname\":\"FA\",\"ctrltype\":\"date\",\"displayname\":\"FA\"}', '{\"ctrlsize\":12,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\",\"cssstyle\":\"FormControl\"}', '{}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseDefinition (Id, ComponentId, CtrlGroupJson, CtrlInfoJson, CtrlPropertiesJson, CtrlSourceJson, IsActive, IsDeleted) VALUES (10038, 26, '{\"ctrlgroupname\":\"VesselInfos\",\"groupsequence\":1}', '{\"ctrlname\":\"Age\",\"ctrltype\":\"range\",\"displayname\":\"Age\"}', '{\"ctrlsize\":12,\"ctrlwidth\":100,\"ctrlheight\":100,\"classname\":\"FormControl\"}', '{}', 1, 0)"
//            };
            
//            foreach (string command in baseDefinitionCommands)
//            {
//                using var cmd = new SqliteCommand(command, connection);
//                cmd.ExecuteNonQuery();
//            }
            
//            Console.WriteLine("BaseDefinition data inserted successfully!");
            
//            // Insert BaseData
//            string[] baseDataCommands = {
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (48, 25, '{\"Name\":\"dsf\",\"Age\":\"44\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (49, 25, '{\"Name\":\"test2\",\"Age\":\"33\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (50, 25, '{\"Name\":\"test3\",\"Age\":\"22\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (51, 14, '{\"AngularVersion\":\"3\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (52, 2, '{\"Name\":\"Name\",\"Age\":\"18\",\"Phone\":\"123456789\",\"Salary\":\"0\"}', 1, 0)",
//                "INSERT OR REPLACE INTO BaseData (Id, ComponentId, BaseData, IsActive, IsDeleted) VALUES (53, 26, '{\"Name\":\"ram\",\"FA\":\"2025-04-07\",\"Age\":\"0\"}', 1, 0)"
//            };
            
//            foreach (string command in baseDataCommands)
//            {
//                using var cmd = new SqliteCommand(command, connection);
//                cmd.ExecuteNonQuery();
//            }
            
//            Console.WriteLine("BaseData inserted successfully!");
            
//            // Verify data
//            using var selectCmd = new SqliteCommand("SELECT COUNT(*) FROM Basecomponent", connection);
//            var baseComponentCount = selectCmd.ExecuteScalar();
//            Console.WriteLine($"Total records in Basecomponent table: {baseComponentCount}");
            
//            using var selectCmd2 = new SqliteCommand("SELECT COUNT(*) FROM BaseDefinition", connection);
//            var baseDefinitionCount = selectCmd2.ExecuteScalar();
//            Console.WriteLine($"Total records in BaseDefinition table: {baseDefinitionCount}");
            
//            using var selectCmd3 = new SqliteCommand("SELECT COUNT(*) FROM BaseData", connection);
//            var baseDataCount = selectCmd3.ExecuteScalar();
//            Console.WriteLine($"Total records in BaseData table: {baseDataCount}");
//        }
//        catch (Exception ex)
//        {
//            Console.WriteLine($"Error: {ex.Message}");
//        }
//    }
//}
