-- Insert data for Basecomponent table
INSERT INTO Basecomponent (Id, ComponentName, ParentComponent, DisplayName, IsActive, IsDeleted, ComponentJson, CustomAttributeJson, IsMaster) VALUES
(2, 'EMP Detail', '16', 'EMP Detail', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(14, 'ContractDetail', '16', 'Contract Detail', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(15, 'Register Form', '16', 'Register Form', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(16, 'DefaultComponent', '0', 'Home', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/jsonformviewer","routerparam": ""}', NULL, 0),
(17, 'addition cost', '16', 'addition cost', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(18, 'Sample Grid', '23', 'AG GRID List', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": "","method": "POST","url": "/api/controllername/getGridData","datasource": [{"Name": "John Doe", "Age": 30}, {"Name": "Jane Smith", "Age": 25},{"Name": "Michael Johnson", "Age": 35}, {"Name": "Emily Davis", "Age": 28}]}', NULL, 0),
(19, 'NatHabbit', '16', 'Nat Habbit', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(20, 'MobileModel', '23', 'Mobile Model', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": "","method": "POST","url": "/api/controllername/getGridData","datasource": [{"brand": "Apple","model": "iPhone 14","os": "iOS","screenSize": "6.1","processor": "A15 Bionic","ram": "6GB","storage": "128GB","battery": "3279mAh","color": "Midnight","price": "799"},{"brand": "Google","model": "Pixel 7","os": "Android","screenSize": "6.3","processor": "Google Tensor G2","ram": "8GB","storage": "128GB","battery": "4355mAh","color": "Obsidian","price": "599"},{"brand": "OnePlus","model": "OnePlus 11","os": "Android","screenSize": "6.7","processor": "Snapdragon 8 Gen 2","ram": "12GB","storage": "256GB","battery": "5000mAh","color": "Titan Black","price": "799"},{"brand": "Samsung","model": "Galaxy Z Flip 5","os": "Android","screenSize": "6.7","processor": "Snapdragon 8 Gen 2","ram": "8GB","storage": "256GB","battery": "3700mAh","color": "Graphite","price": "999"},{"brand": "Xiaomi","model": "Xiaomi 13 Pro","os": "Android","screenSize": "6.73","processor": "Snapdragon 8 Gen 2","ram": "12GB","storage": "256GB","battery": "4820mAh","color": "Ceramic White","price": "899"},{"brand": "Sony","model": "Xperia 1 V","os": "Android","screenSize": "6.5","processor": "Snapdragon 8 Gen 2","ram": "12GB","storage": "256GB","battery": "5000mAh","color": "Black","price": "1199"}]}', NULL, 0),
(21, 'common grid', '23', 'AG GRID Common', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": "","method": "POST","url": "/api/controllername/getGridData","datasource": [{"Name": "John Doe", "Age": 30}, {"Name": "Jane Smith", "Age": 25},{"Name": "Michael Johnson", "Age": 35}, {"Name": "Emily Davis", "Age": 28}]}', NULL, 0),
(22, 'boutique', '16', 'Boutique', 1, 0, '{}', NULL, 0),
(23, 'Grid', '0', 'Grid', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0),
(24, 'string', 'string', 'string', 1, 1, 'string', 'string', 0),
(25, 'MTest', '0', 'Master Test', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 1),
(26, 'Vessel', '0', 'Vessel Detail', 1, 0, '{"menuicon": "far fa-file-alt me-2","routerurl": "/adminconfiguration/baseconfiguration","routerparam": ""}', NULL, 0);
